/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import keeptoo.Drag;

/**
 *
 * @author PC
 */
public class GirisEkrani extends javax.swing.JFrame {
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    final ImageIcon ok_icon = new ImageIcon(getClass().getResource("/iconlar/ok_icon.png"));
    public GirisEkrani() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void girisislemi(){
         try
        {
            conn=db.connect_db();
            String sql="SELECT * FROM KULLANICILAR WHERE KULLANICI_ADI='"+txt_kullanici.getText()+
                    "' AND SIFRE='"+txt_sifre.getText()+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String rol=rs.getString(6);
                Kullanicisim.kullanicisim=rs.getString(2)+" "+rs.getString(3);
                Kullanicisim.rol=rs.getString(6);
                JLabel label = new JLabel("Sayın "+Kullanicisim.kullanicisim+" Hoşgeldiniz!");
                label.setFont(new Font("Segoe UI", Font.BOLD, 15));
                JFrame frame = new JFrame();
                String[] secenekler={"Kontrol Paneli"};
                JOptionPane.showOptionDialog(frame.getContentPane(),label,"Giriş Başarılı",0,JOptionPane.INFORMATION_MESSAGE,ok_icon,secenekler,null);
                rs.close();
                pst.close();
                AnaEkran anaekran=new AnaEkran();
                anaekran.setVisible(true);
                this.setVisible(false);
                this.dispose();
                
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Kullancı adı veya şifre yanlış!");
                txt_sifre.setText("");
            }
        }
        catch(Exception ex)
        {
            
        }
        finally
        {
            try
            {
                conn.close(); 
            }
            catch(Exception ex)
            {
                
            }
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txt_kullanici = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JPasswordField();
        label_kullanici = new javax.swing.JLabel();
        label_sifre = new javax.swing.JLabel();
        btn_giris = new keeptoo.KButton();
        icon_adam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbx_sifregoster = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kullanici.setBackground(new Color(0,0,0,0));
        txt_kullanici.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_kullanici.setForeground(new java.awt.Color(255, 255, 255));
        txt_kullanici.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_kullanici.setOpaque(false);
        kGradientPanel1.add(txt_kullanici, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 380, 40));

        txt_sifre.setBackground(new Color(0,0,0,0));
        txt_sifre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_sifre.setForeground(new java.awt.Color(255, 255, 255));
        txt_sifre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_sifre.setOpaque(false);
        txt_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sifreActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 380, 40));

        label_kullanici.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        label_kullanici.setForeground(new java.awt.Color(204, 204, 204));
        label_kullanici.setText("Kullanıcı Adı");
        kGradientPanel1.add(label_kullanici, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        label_sifre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        label_sifre.setForeground(new java.awt.Color(204, 204, 204));
        label_sifre.setText("Şifre");
        kGradientPanel1.add(label_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        btn_giris.setText("Giriş Yap");
        btn_giris.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_giris.setkBorderRadius(40);
        btn_giris.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_giris.setkHoverEndColor(new java.awt.Color(240, 0, 240));
        btn_giris.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_giris.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_giris.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, -1, -1));

        icon_adam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/girisadam.png"))); // NOI18N
        kGradientPanel1.add(icon_adam, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 473, -1, -1));
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 473, -1, -1));

        label_exit.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        label_exit.setForeground(new java.awt.Color(255, 255, 255));
        label_exit.setText("X");
        label_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_exitMousePressed(evt);
            }
        });
        kGradientPanel1.add(label_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 0, 27, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/logo.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 296));

        cbx_sifregoster.setBackground(new Color(0,0,0,0)
        );
        cbx_sifregoster.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cbx_sifregoster.setForeground(new java.awt.Color(204, 204, 204));
        cbx_sifregoster.setText("Şifreyi Göster");
        cbx_sifregoster.setOpaque(false);
        cbx_sifregoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_sifregosterActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cbx_sifregoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
    girisislemi();
    }//GEN-LAST:event_btn_girisActionPerformed

    private void label_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMousePressed
       System.exit(0);
    }//GEN-LAST:event_label_exitMousePressed

    private void cbx_sifregosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_sifregosterActionPerformed
         if (cbx_sifregoster.isSelected()) {
            txt_sifre.setEchoChar((char)0);
        }
        else{
            txt_sifre.setEchoChar('*');
        }
    }//GEN-LAST:event_cbx_sifregosterActionPerformed

    private void txt_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sifreActionPerformed
    girisislemi();
    }//GEN-LAST:event_txt_sifreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_giris;
    private javax.swing.JCheckBox cbx_sifregoster;
    private javax.swing.JLabel icon_adam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel label_exit;
    private javax.swing.JLabel label_kullanici;
    private javax.swing.JLabel label_sifre;
    private javax.swing.JTextField txt_kullanici;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
